[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node", "ruby", "python"]

[tools]
"npm:prettier" = "latest"

node = "24.12.0"
pnpm = "latest"
python = "3.13.0"
ruby = "4.0.1"
yarn = "4.12.0"
